export const QUERY_KEY = {
  SOCIAL_DETAIL: 'social-detail',
  SOCIAL_PARTICIPANTS: 'social-participants',
  SOCIAL_PARTICIPANTS_BY_DB: 'social-participants-by-db',
  GET_SUMMARY: 'get-summary',
  GET_USER_ROLE: 'get-user-role',
  GET_APPROVE_USER: 'get-approve-user',
  GET_CONTENTS: 'get-contents',
  GET_LAST_CONTENT: 'get-last-content',
  SOCIAL: 'social',
  SOCIAL_SUMMARY: 'social-summary',
  MY_INFO: 'my-info',
  IS_LIKED: 'is-liked',
  LIKE_COUNT: 'like-count',
} as const;
