export const QUERY_KEY = {
  SOCIAL_DETAIL: 'social-detail',
  SOCIAL_PARTICIPANTS: 'social-participants',
  SOCIAL_PARTICIPANTS_BY_DB: 'social-participants-by-db',
  GET_STORIES: 'get-stories',
  COLLABORATOR_LIST: 'collaborator-list',
  GET_SUMMARY: 'get-summary',
  GET_USER_ROLE: 'get-user-role',
  GET_APPROVE_USER: 'get-approve-user',
  GET_CONTENTS: 'get-contents',
  GET_LAST_CONTENT: 'get-last-content',
  GET_STORY_COLLABORATORS: 'get-story-collaborators',
  SOCIAL: 'social',
  SOCIAL_SUMMARY: 'social-summary',
  MY_INFO: 'my-info',
} as const;
