name: Build We-Write Workflow

on: push
jobs:
  build-project:
    name: Build We-Write Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
